# Generated by Django 2.1.4 on 2019-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('is_dir', models.BooleanField()),
                ('size', models.PositiveIntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
