# Generated by Django 2.1.4 on 2019-01-13 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190113_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='path',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_with',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
