# Generated by Django 2.1.4 on 2019-01-14 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190114_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='filename',
            field=models.CharField(default='.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_with',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
