# Generated by Django 2.1.5 on 2019-01-20 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_sharedfile_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedfile',
            options={'ordering': ('filename',)},
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='filename',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='is_dir',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
