# Generated by Django 2.1.5 on 2019-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_downloadstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadstatistic',
            name='filename',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadstatistic',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='downloadstatistic',
            name='path',
            field=models.CharField(default='/', max_length=512),
        ),
    ]
